// import translate from 'translate-google';

export const LANGUAGES = {
	af: 'Afrikaans',
	ar: 'Arabic',
	auto: 'Automatic',
	az: 'Azerbaijani',
	be: 'Belarusian',
	bg: 'Bulgarian',
	bn: 'Bengali',
	bs: 'Bosnian',
	ca: 'Catalan',
	ceb: 'Cebuano',
	co: 'Corsican',
	cs: 'Czech',
	cy: 'Welsh',
	da: 'Danish',
	de: 'German',
	el: 'Greek',
	en: 'English',
	eo: 'Esperanto',
	es: 'Spanish',
	et: 'Estonian',
	eu: 'Basque',
	fa: 'Persian',
	fi: 'Finnish',
	fr: 'French',
	fy: 'Frisian',
	ga: 'Irish',
	gd: 'Scots Gaelic',
	gl: 'Galician',
	gu: 'Gujarati',
	ha: 'Hausa',
	haw: 'Hawaiian',
	hi: 'Hindi',
	hmn: 'Hmong',
	hr: 'Croatian',
	ht: 'Haitian Creole',
	hu: 'Hungarian',
	hy: 'Armenian',
	id: 'Indonesian',
	ig: 'Igbo',
	is: 'Icelandic',
	it: 'Italian',
	iw: 'Hebrew',
	ja: 'Japanese',
	jw: 'Javanese',
	ka: 'Georgian',
	kk: 'Kazakh',
	km: 'Khmer',
	kn: 'Kannada',
	ko: 'Korean',
	ku: 'Kurdish (Kurmanji)',
	ky: 'Kyrgyz',
	la: 'Latin',
	lb: 'Luxembourgish',
	lo: 'Lao',
	lt: 'Lithuanian',
	lv: 'Latvian',
	ma: 'Punjabi',
	mg: 'Malagasy',
	mi: 'Maori',
	mk: 'Macedonian',
	ml: 'Malayalam',
	mn: 'Mongolian',
	mr: 'Marathi',
	ms: 'Malay',
	mt: 'Maltese',
	my: 'Myanmar (Burmese)',
	ne: 'Nepali',
	nl: 'Dutch',
	no: 'Norwegian',
	ny: 'Chichewa',
	pl: 'Polish',
	ps: 'Pashto',
	pt: 'Portuguese',
	ro: 'Romanian',
	ru: 'Russian',
	sd: 'Sindhi',
	si: 'Sinhala',
	sk: 'Slovak',
	sl: 'Slovenian',
	sm: 'Samoan',
	sn: 'Shona',
	so: 'Somali',
	sq: 'Albanian',
	sr: 'Serbian',
	st: 'Sesotho',
	su: 'Sudanese',
	sv: 'Swedish',
	sw: 'Swahili',
	ta: 'Tamil',
	te: 'Telugu',
	tg: 'Tajik',
	th: 'Thai',
	tl: 'Filipino',
	tr: 'Turkish',
	uk: 'Ukrainian',
	ur: 'Urdu',
	uz: 'Uzbek',
	vi: 'Vietnamese',
	xh: 'Xhosa',
	yi: 'Yiddish',
	yo: 'Yoruba',
	'zh-cn': 'Chinese Simplified',
	'zh-tw': 'Chinese Traditional',
	zu: 'Zulu',
} as const;

export const LANGUAGES2 = [
	{
		code: 'ar',
		englishName: 'Arabic',
		nativeName: 'العربية',
	},
	{
		code: 'as',
		englishName: 'Assamese',
		nativeName: 'Assamese',
	},
	{
		code: 'bg',
		englishName: 'Bulgarian',
		nativeName: 'Български',
	},
	{
		code: 'bn',
		englishName: 'Bangla',
		nativeName: 'বাংলা',
	},
	{
		code: 'ca',
		englishName: 'Catalan',
		nativeName: 'Català',
	},
	{
		code: 'cs',
		englishName: 'Czech',
		nativeName: 'Čeština',
	},
	{
		code: 'da',
		englishName: 'Danish',
		nativeName: 'Dansk',
	},
	{
		code: 'de',
		englishName: 'German',
		nativeName: 'Deutsch',
	},
	{
		code: 'el',
		englishName: 'Greek',
		nativeName: 'Ελληνικά',
	},
	{
		code: 'en',
		englishName: 'English',
		nativeName: 'English',
	},
	{
		code: 'es',
		englishName: 'Spanish',
		nativeName: 'Español',
	},
	{
		code: 'fa',
		englishName: 'Persian',
		nativeName: 'Persian',
	},
	{
		code: 'fi',
		englishName: 'Finnish',
		nativeName: 'Suomi',
	},
	{
		code: 'fil',
		englishName: 'Filipino',
		nativeName: 'Filipino',
	},
	{
		code: 'fr-fr',
		englishName: 'French',
		nativeName: 'Français',
	},
	{
		code: 'fr-ca',
		englishName: 'French (Canada)',
		nativeName: 'French (Canada)',
	},
	{
		code: 'gu',
		englishName: 'Gujarati',
		nativeName: 'ગુજરાતી',
	},
	{
		code: 'he',
		englishName: 'Hebrew',
		nativeName: 'עברית',
	},
	{
		code: 'hi',
		englishName: 'Hindi',
		nativeName: 'हिंदी',
	},
	{
		code: 'hr',
		englishName: 'Croatian',
		nativeName: 'Hrvatski',
	},
	{
		code: 'ht',
		englishName: 'Haitian Creole',
		nativeName: 'Haitian Creole',
	},
	{
		code: 'hu',
		englishName: 'Hungarian',
		nativeName: 'Magyar',
	},
	{
		code: 'id',
		englishName: 'Indonesian',
		nativeName: 'Indonesia',
	},
	{
		code: 'it',
		englishName: 'Italian',
		nativeName: 'Italiano',
	},
	{
		code: 'ja',
		englishName: 'Japanese',
		nativeName: '日本語',
	},
	{
		code: 'kk',
		englishName: 'Kazakh',
		nativeName: 'Kazakh',
	},
	{
		code: 'kn',
		englishName: 'Kannada',
		nativeName: 'ಕನ್ನಡ',
	},
	{
		code: 'ko',
		englishName: 'Korean',
		nativeName: '한국어',
	},
	{
		code: 'lt',
		englishName: 'Lithuanian',
		nativeName: 'Lietuvių',
	},
	{
		code: 'mg',
		englishName: 'Malagasy',
		nativeName: 'Malagasy',
	},
	{
		code: 'ml',
		englishName: 'Malayalam',
		nativeName: 'മലയാളം',
	},
	{
		code: 'mr',
		englishName: 'Marathi',
		nativeName: 'मराठी',
	},
	{
		code: 'ms',
		englishName: 'Malay',
		nativeName: 'Melayu',
	},
	{
		code: 'nb',
		englishName: 'Norwegian',
		nativeName: 'Norsk',
	},
	{
		code: 'nl',
		englishName: 'Dutch',
		nativeName: 'Nederlands',
	},
	{
		code: 'or',
		englishName: 'Odia',
		nativeName: 'Odia',
	},
	{
		code: 'pa',
		englishName: 'Punjabi',
		nativeName: 'ਪੰਜਾਬੀ',
	},
	{
		code: 'pl',
		englishName: 'Polish',
		nativeName: 'Polski',
	},
	{
		code: 'ps',
		englishName: 'Pashto',
		nativeName: 'Pashto',
	},
	{
		code: 'pt-br',
		englishName: 'Portuguese (Brazil)',
		nativeName: 'Português (Brasil)',
	},
	{
		code: 'pt-pt',
		englishName: 'Portuguese (Portugal)',
		nativeName: 'Português (Portugal)',
	},
	{
		code: 'ro',
		englishName: 'Romanian',
		nativeName: 'Română',
	},
	{
		code: 'ru',
		englishName: 'Russian',
		nativeName: 'Русский',
	},
	{
		code: 'sk',
		englishName: 'Slovak',
		nativeName: 'Slovenčina',
	},
	{
		code: 'sl',
		englishName: 'Slovenian',
		nativeName: 'Slovenščina',
	},
	{
		code: 'sv',
		englishName: 'Swedish',
		nativeName: 'Svenska',
	},
	{
		code: 'sw',
		englishName: 'Swahili',
		nativeName: 'Kiswahili',
	},
	{
		code: 'ta',
		englishName: 'Tamil',
		nativeName: 'தமிழ்',
	},
	{
		code: 'te',
		englishName: 'Telugu',
		nativeName: 'తెలుగు',
	},
	{
		code: 'th',
		englishName: 'Thai',
		nativeName: 'ไทย',
	},
	{
		code: 'tr',
		englishName: 'Turkish',
		nativeName: 'Türkçe',
	},
	{
		code: 'uk',
		englishName: 'Ukrainian',
		nativeName: 'Українська',
	},
	{
		code: 'ur',
		englishName: 'Urdu',
		nativeName: 'اردو',
	},
	{
		code: 'vi',
		englishName: 'Vietnamese',
		nativeName: 'Tiếng Việt',
	},
	{
		code: 'zh-Hans',
		englishName: 'Chinese (Simplified)',
		nativeName: '简体中文',
	},
	{
		code: 'zh-Hant',
		englishName: 'Chinese (Traditional)',
		nativeName: '繁體中文',
	},
] as const;

export type LanguageKey = keyof typeof LANGUAGES;

export const LANGUAGES_ARRAY = Object.values(LANGUAGES);
